### ISSUE TITLE
به روز نبودن نسخه دبیان

### ISSUE THREAD

**Issue by goyban** [MohammadRostamiorg/dnsChanger#11]
درود
من قصد دارم این اسکریپ را معرفی کنم ولی دارم از لینوکس مینت استفاده می‌کنم، پکیج .deb آپدیت نیست و تمام آپشن‌ها را نداره.

پکیج دبیان:
sudo dnsch 
Usage: /usr/bin/dnsch {g|sh|ag|cf|403|bg}

اسکریپ اصلی:
sudo ./dnsch.sh 
Usage: ./dnsch.sh {g|sh|ag|cf|403|bg|rd|el} [-c|--clear] [-s|--set] [-p|--ping] [-r|--restore]

**Comment by AliAlmasi** [comment]
سلام
آیا  دارین از [آخرین نسخه](https://github.com/MohammadRostamiorg/dnsChanger/releases/latest) استفاده میکنین؟
میشه لطفا بگین از کدوم نسخه دارین استفاده میکنین؟

**Comment by goyban** [comment]
> سلام آیا دارین از [آخرین نسخه](https://github.com/MohammadRostamiorg/dnsChanger/releases/latest) استفاده میکنین؟ میشه لطفا بگین از کدوم نسخه دارین استفاده میکنین؟

بله آخرین نسخه است، دقت کنید خودم بیلد نکردم (در صورت بیلد کردن مشکلی نداره) به عنوان کاربر لینوکس مینت فقط پکیج دبیان را دانلود کردم.
به نظر تغییرات نهایی روی باینری dnsch.deb اعمال نشده.

**Comment by AliAlmasi** [comment]
@MohammadRostamiorg

بیلد دبیان روی آخرین تغییرات انجام نشده؟ (خودم دبیان ندارم وگرنه تست میکردم. دارم مینت دانلود میکنم فعلا.)

**Comment by MohammadRostamiorg** [comment]
سلام 
خیلی‌ ممنون از معرفی و نظرتون 
حل شد
