### ISSUE TITLE
مشکل در کلیر دی ان اس سرور ها

### ISSUE THREAD

**Issue by aligholipour1** [MohammadRostamiorg/dnsChanger#8]
سلام زمانی که من دی ان اس سرور ها رو کلیر میکنم کلا محتویات فایل resolv.conf رو پاک میکنه و من مجبورم که حتما networkmanager رو ری استارت کنم میتونید یه کاری بکنید که لازم نباشه networkmanager رو ری استارت کرد؟

**Comment by MohammadRostamiorg** [comment]
سلام 

کلیر خب کارش اینه که بیاد resolv.conf رو پاک کنه 

ولی اگه میخوای dns های دیفالت رو ست کنی
وقت کنم یه اپشن جدید میزنم که بیاد و dns های دیفالت نتورک منیجر رو دوباره ست کنه
